### ISSUE TITLE
메타데이터 5종 하드코딩

### ISSUE THREAD

**Issue by pangnem** [wise-pangnem/AutoMLMainWeb#237]
공인인증 시험을 위해 5종에 대해 바로 메타데이터가 입력되도록 처리해야 합니다.

**Comment by choitaedong2** [comment]
1. 
[ETC_79_04_01_510483.csv](https://github.com/wise-pangnem/AutoMLMainWeb/files/9256863/ETC_79_04_01_510483.csv)
2.
[ETC_78_04_01_371837.csv](https://github.com/wise-pangnem/AutoMLMainWeb/files/9256868/ETC_78_04_01_371837.csv)
3. 
[VDS_38_01_01_210028.csv](https://github.com/wise-pangnem/AutoMLMainWeb/files/9256869/VDS_38_01_01_210028.csv)
4.
[VDS_23_01_01_570513.csv](https://github.com/wise-pangnem/AutoMLMainWeb/files/9256870/VDS_23_01_01_570513.csv)
5.
[SURFACE_ASOS_95_MI_2022-01_2022-01_2022.csv](https://github.com/wise-pangnem/AutoMLMainWeb/files/9256873/SURFACE_ASOS_95_MI_2022-01_2022-01_2022.csv)

**Comment by choitaedong2** [comment]
[메타데이터 정리.pdf](https://github.com/wise-pangnem/AutoMLMainWeb/files/9256886/default.pdf)

- 한글 파일이 지원이 안되서 PDF로 드렸는데, 보시고 슬랙으로 코멘트 주세요
