### ISSUE TITLE
관리자페이지 수정 사항

### ISSUE THREAD

**Issue by choitaedong2** [wise-pangnem/AutoMLMainWeb#269]
![image](https://user-images.githubusercontent.com/72964955/190319507-ac768e56-308c-4871-906a-a49c2513d92d.png)
1. `AutoML` -> `WS-AutoML 관리자 페이지`
2. 대시 보드 삭제
 - 대시 보드 이동 링크 -> 메타데이터 관리 페이지로 변경
3. `메인화면` -> `WS-AutoML`
4. `유저` -> `유저관리`

---
![image](https://user-images.githubusercontent.com/72964955/190320257-617ba1fc-4e87-4c9e-b721-1dd7dde7c5ee.png)
1. 변경 가능한 권한 중 'USER 권한' 삭제
2. `유저` -> `유저관리`
---
![image](https://user-images.githubusercontent.com/72964955/190320659-f73e110e-1de8-427e-a499-020dc7cc4747.png)
1. 업로드, 삭제하기 버튼과 테이블 사이에 '메타데이터 리스트' 텍스트 추가
---
![image](https://user-images.githubusercontent.com/72964955/190321316-8d773f9f-3f1e-47ef-a9a7-228678f2c228.png)
1. 라이센스, 권한 부분 변경
 - `권한` -> `공개`
*****  `ALL, CLUST Con~~~` -> `Yes, No`
 - 일단 킵
 ---
![image](https://user-images.githubusercontent.com/72964955/190321947-f8ac0f00-8eea-43f6-baf4-1bb443953baa.png)
1. 디폴트 값 설정

**Comment by choitaedong2** [comment]
![image](https://user-images.githubusercontent.com/72964955/190335989-f77a6ec8-132d-4d00-ac51-3c22ad51c3ec.png)
1. 첫 페이지 제작 필요
 - `개발 예정` -> `관리자를 위한 페이지 입니다.` 라는 식의 관리자 메인 페이지가 필요합니다.
 * `대시 보드` 페이지 삭제 후 첫 페이지가 메타데이터 관리 페이지로 이동하면 안됨

**Comment by pangnem** [comment]
### 대시보드 관련 내용
대시보드 관련 링크를 삭제하고, 첫번째 페이지에 `관리자를 위한 페이지입니다` alert로 변경

**Comment by pangnem** [comment]
- [ ] AutoML -> WS-AutoML 관리자 페이지
- [ ] 대시 보드 삭제
- [ ] 대시 보드 이동 링크 -> 메타데이터 관리 페이지로 변경
- [ ] 메인화면 -> WS-AutoML
- [ ] 유저 -> 유저관리
- [ ] 변경 가능한 권한 중 'USER 권한' 삭제
- [ ] 업로드, 삭제하기 버튼과 테이블 사이에 '메타데이터 리스트' 텍스트 추가
- [ ] 디폴트 값 설정

**Comment by choitaedong2** [comment]
![image](https://user-images.githubusercontent.com/72964955/190650206-c3df95f0-8e18-4b00-9f2c-8b91f0dce05d.png)
URL 입력시, 미입력시 상관없이 기본 디폴트 값 설정 내용

**Comment by choitaedong2** [comment]
`*필수입력* ~~~~~~`
- 카테고리
- 주제
- 제목
- 구축기관
- 생성기관
- 담당자 이름
- 유형
- 키워드
- 라이센스,
- 권한,
- 데이터셋 설명
- 배포 설명
- 시간단위

**Comment by choitaedong2** [comment]
![image](https://user-images.githubusercontent.com/72964955/190654610-78d12551-ae5b-43d5-8321-98f264229cc4.png)
`관리자를 위한 페이지 입니다`
`허가 받지 않은 사용자는 접속이 제한됩니다`

**Comment by pangnem** [comment]
- [ ] 필수 입력값 재조정
- [ ] 필수 입력값 앞에 별표 표시
- [ ] 측정 단위를 `시간단위(ex. 1분, 5분, 15분, 30분, 1시간, 6시간, 1일)`로 텍스트 변경
- [ ] 로그인 카드 텍스트 변경 `관리자 전용 페이지로 허가 받은 사용자만 접속이 가능합니다.`

**Comment by pangnem** [comment]
- [ ] 타이틀 변경 `AutoML` => `WS-AutoML 관리자 페이지`
