### ISSUE TITLE
검색 페이지 수정 사항

### ISSUE THREAD

**Issue by choitaedong2** [wise-pangnem/AutoMLMainWeb#271]
![image](https://user-images.githubusercontent.com/72964955/190323176-12a189cb-84d0-41b3-84b8-88422c5636a2.png)
1. `검색` 버튼 추가
---
2. 데이터 첫 페이지 수정

**Comment by pangnem** [comment]
- [ ] 검색 버튼 추가
- [ ] **총** n건의 데이터를 찾았습니다로 문구 변경
