### ISSUE TITLE
데이터 상세 페이지 수정 사항

### ISSUE THREAD

**Issue by choitaedong2** [wise-pangnem/AutoMLMainWeb#272]
![image](https://user-images.githubusercontent.com/72964955/190324914-e29265c5-0951-407a-808b-5fc1ed27f52c.png)
1. `배포| 다운로드 URL` -> 제거
 1-1 메타데이터 다운로드 옆에 다운로드 버튼 생성
2. `메타데이터 다운로드` -> `메타데이터 다운로드(Json)`

**Comment by pangnem** [comment]
- [ ] `배포| 다운로드 URL` -> 제거
  - [ ] 1-1 메타데이터 다운로드 옆에 다운로드 버튼 생성
- [ ] 메타데이터 다운로드 -> 메타데이터 다운로드(Json)

**Comment by pangnem** [comment]
관련 이슈 및 PR
- #266
- #267

**Comment by pangnem** [comment]
#278

**Comment by pangnem** [comment]
- #281
